# Generated by Django 4.1.7 on 2023-02-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='message',
            field=models.CharField(max_length=30),
        ),
    ]
