# Generated by Django 4.1.7 on 2023-02-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dmail_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmail',
            name='message',
            field=models.CharField(max_length=20),
        ),
    ]
