# Generated by Django 4.1.7 on 2023-03-11 15:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_chat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(default='media/image/noimage.png', upload_to=core.models.upload_diary_path),
        ),
    ]
