# Generated by Django 4.1.7 on 2023-03-30 14:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_diary_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='diary',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='diary',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='diary',
            old_name='user_id',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='dmail',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='dmail',
            old_name='get_user',
            new_name='getUser',
        ),
        migrations.RenameField(
            model_name='dmail',
            old_name='send_user',
            new_name='sendUser',
        ),
        migrations.RenameField(
            model_name='dmail',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='groupin',
            old_name='show_user',
            new_name='showUser',
        ),
        migrations.RenameField(
            model_name='groupin',
            old_name='target_group',
            new_name='targetGroup',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.AlterUniqueTogether(
            name='groupin',
            unique_together={('showUser', 'targetGroup')},
        ),
    ]
